export const FETCH_DASHBOARDS = 'FETCH_DASHBOARDS';
export const FETCH_DASHBOARDS_SUCCESS = 'FETCH_DASHBOARDS_SUCCESS';
export const FETCH_DASHBOARDS_ERROR = 'FETCH_DASHBOARDS_ERROR';

export const RESET_DASHBOARDS_NOTIFICATIONS = 'RESET_DASHBOARDS_NOTIFICATIONS';
