export const FETCH_VISUALIZATIONS = 'FETCH_VISUALIZATIONS';
export const FETCH_VISUALIZATIONS_SUCCESS = 'FETCH_VISUALIZATIONS_SUCCESS';
export const FETCH_VISUALIZATIONS_ERROR = 'FETCH_VISUALIZATIONS_ERROR';

export const RESET_VISUALIZATIONS_NOTIFICATIONS =
  'RESET_VISUALIZATIONS_NOTIFICATIONS';
