export const FETCH_COLLECTION = 'FETCH_COLLECTION';
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS';
export const FETCH_COLLECTION_ERROR = 'FETCH_COLLECTION_ERROR';

export const RESET_COLLECTION_NOTIFICATIONS = 'RESET_COLLECTION_NOTIFICATIONS';
