export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_ERROR = 'FETCH_COLLECTIONS_ERROR';

export const RESET_COLLECTIONS_NOTIFICATIONS =
  'RESET_COLLECTIONS_NOTIFICATIONS';
