export const FETCH_DASHBOARD = 'FETCH_DASHBOARD';
export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS';
export const FETCH_DASHBOARD_ERROR = 'FETCH_DASHBOARD_ERROR';

export const RESET_DASHBOARD_NOTIFICATIONS = 'RESET_DASHBOARD_NOTIFICATIONS';
