export const FETCH_VISUALIZATION = 'FETCH_VISUALIZATION';
export const FETCH_VISUALIZATION_SUCCESS = 'FETCH_VISUALIZATION_SUCCESS';
export const FETCH_VISUALIZATION_ERROR = 'FETCH_VISUALIZATION_ERROR';

export const RESET_VISUALIZATION_NOTIFICATIONS =
  'RESET_VISUALIZATION_NOTIFICATIONS';
